apiVersion: v1
kind: Pod
metadata:
  name: busybox-lineage
  namespace: default
  labels:
    name: busybox-lineage
spec:
  containers:
    - name: busybox-lineage
      image: busybox
      command: ["/bin/sh", "-c", "while true;do sleep 5; echo sleep; done"]
      volumeMounts:
        - mountPath: /usr/share/busybox
          name: test
      resources:
        limits:
          memory: "64Mi"
          cpu: "50m"
  volumes:
    - name: test
      persistentVolumeClaim:
        claimName: lineage-test