apiVersion: v1
kind: Pod
metadata:
  name: sickpod-oom-example
  namespace: default
spec:
  containers:
  - name: memory-demo-ctr
    image: polinux/stress
    resources:
      requests:
        cpu: "0.3"
        memory: "100Mi"
      limits:
        cpu: "0.3"
        memory: "100Mi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]
